version: '3.2'
services:

  zabbix-db:
    image: mysql:latest
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    volumes:
      - /docker/volumes/mysql:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin
    ports:
      - 3306:3306
    container_name: zabbix-db